## 服务相关
server:
  port: 8088
  servlet:
    context-path: /uccp
  tomcat:
    accept-count: 1000
    max-connections: 1000
    threads:
      min-spare: 2
      max: 1000

## 应用相关
app:
  log-home: logs/logback # 日志记录根目录位置
  db-log-level: info # 记录到数据库的日志级别。trace>debug>info>warn>error

## spring相关配置信息
spring:
#  mvc:
#    static-path-pattern: classpath:/static/
  thymeleaf:
    cache: false #测试环境关闭缓存
    prefix: classpath:/templates/
  datasource:
    druid:
      url: jdbc:mysql://10.10.49.103:3306/uccp_test?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
      username: icomp
      password: icomp
      driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: 10.10.48.104
    port: 6379
    database: 0
    jedis:
      pool:
        max-active: -1
        max-wait: -1
        max-idle: 10
        min-idle: 0
    timeout: 2000


mybatis-plus:
  type-aliases-package: com.nantian.entity #配置mybatis映射文件中实体类的别名
  mapper-locations: classpath:/mapper/*.xml
logging:
  level:
    com:
      nantian:
        dao: debug
